title: Προσωπικό ιστολόγιο
author: Μιχάλης Μαθιουδάκης
theme: minima
description: Εργάζομαι ως αναπληρωτής καθηγητής πληροφορικής στο Πανεπιστήμιο του Ελσίνκι ([ιστοσελίδα](https://researchportal.helsinki.fi/en/persons/michael-mathioudakis)). Μπορείτε επίσης να με βρείτε στο [Χ](https://x.com/mmathioudakis). Σε αυτό το ιστολόγιο γράφω στα ελληνικά.

